app:
    default:
        price: 0
    users:
        default:
            balance: 0
server:
    port: 80
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: amigoscode
        url: jdbc:postgresql://localhost:5433/postgres
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
